version: '3'

services:
  camunda:
    build:
      context: ./camunda
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - camunda-data:/opt/app/db
    networks:
      - backend
    restart: always

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always

  recommender-system:
    build:
      context: ./recommender-system
      dockerfile: Dockerfile
    depends_on:
      camunda:
        condition: service_healthy
    networks:
      - backend
    restart: always

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  camunda-data:
  mariadb-data:

networks:
  backend:
    driver: bridge