version: '3'

services:
  engine:
    build:
      context: ./Engine
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    volumes:
      - camunda-db:/opt/app/db

volumes:
  camunda-db: